# -*- coding: utf-8 -*-
"""linear regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LMrVvN7nFddLAb4aTVt8_QK-Y2fS_xTN
"""

from google.colab import drive

drive.mount('/content/drive/')

import pandas as pd
import joblib
from sklearn.linear_model import LinearRegression



df=pd.read_excel('/content/drive/MyDrive/LinearRegression.xlsx')

df

x = df[['dis']].values

y = df['act fare']

lr = LinearRegression()

lr.fit(x, y)

lr.intercept_

lr.coef_

lr.predict([[10] ,[11]])

joblib.dump(lr, 'LinearRegressionmodel.joblib')